//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DHPO_Auditor.DHPO {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.eClaimLink.ae/", ConfigurationName="DHPO.ValidateTransactionsSoap")]
    public interface ValidateTransactionsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        DHPO_Auditor.DHPO.GetNewTransactionsResponse GetNewTransactions(DHPO_Auditor.DHPO.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewTransactionsResponse> GetNewTransactionsAsync(DHPO_Auditor.DHPO.GetNewTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse GetNewPriorAuthorizationTransactions(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/GetNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadTransaction", ReplyAction="*")]
        DHPO_Auditor.DHPO.UploadTransactionResponse UploadTransaction(DHPO_Auditor.DHPO.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/UploadTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.UploadTransactionResponse> UploadTransactionAsync(DHPO_Auditor.DHPO.UploadTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        DHPO_Auditor.DHPO.DownloadTransactionFileResponse DownloadTransactionFile(DHPO_Auditor.DHPO.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/DownloadTransactionFile", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.DownloadTransactionFileResponse> DownloadTransactionFileAsync(DHPO_Auditor.DHPO.DownloadTransactionFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse CheckForNewPriorAuthorizationTransactions(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/CheckForNewPriorAuthorizationTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        DHPO_Auditor.DHPO.SetTransactionDownloadedResponse SetTransactionDownloaded(DHPO_Auditor.DHPO.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SetTransactionDownloaded", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(DHPO_Auditor.DHPO.SetTransactionDownloadedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        DHPO_Auditor.DHPO.SearchTransactionsResponse SearchTransactions(DHPO_Auditor.DHPO.SearchTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.eClaimLink.ae/SearchTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SearchTransactionsResponse> SearchTransactionsAsync(DHPO_Auditor.DHPO.SearchTransactionsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.GetNewTransactionsRequestBody Body;
        
        public GetNewTransactionsRequest() {
        }
        
        public GetNewTransactionsRequest(DHPO_Auditor.DHPO.GetNewTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewTransactionsRequestBody() {
        }
        
        public GetNewTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.GetNewTransactionsResponseBody Body;
        
        public GetNewTransactionsResponse() {
        }
        
        public GetNewTransactionsResponse(DHPO_Auditor.DHPO.GetNewTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewTransactionsResponseBody() {
        }
        
        public GetNewTransactionsResponseBody(int GetNewTransactionsResult, string xmlTransaction, string errorMessage) {
            this.GetNewTransactionsResult = GetNewTransactionsResult;
            this.xmlTransaction = xmlTransaction;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequestBody Body;
        
        public GetNewPriorAuthorizationTransactionsRequest() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequest(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public GetNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewPriorAuthorizationTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponseBody Body;
        
        public GetNewPriorAuthorizationTransactionsResponse() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponse(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class GetNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string xmlTransaction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public GetNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public GetNewPriorAuthorizationTransactionsResponseBody(int GetNewPriorAuthorizationTransactionsResult, string xmlTransaction, string errorMessage) {
            this.GetNewPriorAuthorizationTransactionsResult = GetNewPriorAuthorizationTransactionsResult;
            this.xmlTransaction = xmlTransaction;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransaction", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.UploadTransactionRequestBody Body;
        
        public UploadTransactionRequest() {
        }
        
        public UploadTransactionRequest(DHPO_Auditor.DHPO.UploadTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] fileContent;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fileName;
        
        public UploadTransactionRequestBody() {
        }
        
        public UploadTransactionRequestBody(string login, string pwd, byte[] fileContent, string fileName) {
            this.login = login;
            this.pwd = pwd;
            this.fileContent = fileContent;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadTransactionResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.UploadTransactionResponseBody Body;
        
        public UploadTransactionResponse() {
        }
        
        public UploadTransactionResponse(DHPO_Auditor.DHPO.UploadTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class UploadTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UploadTransactionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] errorReport;
        
        public UploadTransactionResponseBody() {
        }
        
        public UploadTransactionResponseBody(int UploadTransactionResult, string errorMessage, byte[] errorReport) {
            this.UploadTransactionResult = UploadTransactionResult;
            this.errorMessage = errorMessage;
            this.errorReport = errorReport;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFile", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.DownloadTransactionFileRequestBody Body;
        
        public DownloadTransactionFileRequest() {
        }
        
        public DownloadTransactionFileRequest(DHPO_Auditor.DHPO.DownloadTransactionFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileId;
        
        public DownloadTransactionFileRequestBody() {
        }
        
        public DownloadTransactionFileRequestBody(string login, string pwd, string fileId) {
            this.login = login;
            this.pwd = pwd;
            this.fileId = fileId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadTransactionFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadTransactionFileResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.DownloadTransactionFileResponseBody Body;
        
        public DownloadTransactionFileResponse() {
        }
        
        public DownloadTransactionFileResponse(DHPO_Auditor.DHPO.DownloadTransactionFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class DownloadTransactionFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DownloadTransactionFileResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] file;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errorMessage;
        
        public DownloadTransactionFileResponseBody() {
        }
        
        public DownloadTransactionFileResponseBody(int DownloadTransactionFileResult, string fileName, byte[] file, string errorMessage) {
            this.DownloadTransactionFileResult = DownloadTransactionFileResult;
            this.fileName = fileName;
            this.file = file;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsRequest() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequest(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class CheckForNewPriorAuthorizationTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsRequestBody(string login, string pwd) {
            this.login = login;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckForNewPriorAuthorizationTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckForNewPriorAuthorizationTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponseBody Body;
        
        public CheckForNewPriorAuthorizationTransactionsResponse() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponse(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class CheckForNewPriorAuthorizationTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CheckForNewPriorAuthorizationTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody() {
        }
        
        public CheckForNewPriorAuthorizationTransactionsResponseBody(int CheckForNewPriorAuthorizationTransactionsResult, string errorMessage) {
            this.CheckForNewPriorAuthorizationTransactionsResult = CheckForNewPriorAuthorizationTransactionsResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloaded", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.SetTransactionDownloadedRequestBody Body;
        
        public SetTransactionDownloadedRequest() {
        }
        
        public SetTransactionDownloadedRequest(DHPO_Auditor.DHPO.SetTransactionDownloadedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fieldId;
        
        public SetTransactionDownloadedRequestBody() {
        }
        
        public SetTransactionDownloadedRequestBody(string login, string pwd, string fieldId) {
            this.login = login;
            this.pwd = pwd;
            this.fieldId = fieldId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetTransactionDownloadedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetTransactionDownloadedResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.SetTransactionDownloadedResponseBody Body;
        
        public SetTransactionDownloadedResponse() {
        }
        
        public SetTransactionDownloadedResponse(DHPO_Auditor.DHPO.SetTransactionDownloadedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SetTransactionDownloadedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SetTransactionDownloadedResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public SetTransactionDownloadedResponseBody() {
        }
        
        public SetTransactionDownloadedResponseBody(int SetTransactionDownloadedResult, string errorMessage) {
            this.SetTransactionDownloadedResult = SetTransactionDownloadedResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactions", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.SearchTransactionsRequestBody Body;
        
        public SearchTransactionsRequest() {
        }
        
        public SearchTransactionsRequest(DHPO_Auditor.DHPO.SearchTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int direction;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callerLicense;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ePartner;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int transactionID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int TransactionStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string transactionFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string transactionFromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string transactionToDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int minRecordCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int maxRecordCount;
        
        public SearchTransactionsRequestBody() {
        }
        
        public SearchTransactionsRequestBody(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            this.login = login;
            this.pwd = pwd;
            this.direction = direction;
            this.callerLicense = callerLicense;
            this.ePartner = ePartner;
            this.transactionID = transactionID;
            this.TransactionStatus = TransactionStatus;
            this.transactionFileName = transactionFileName;
            this.transactionFromDate = transactionFromDate;
            this.transactionToDate = transactionToDate;
            this.minRecordCount = minRecordCount;
            this.maxRecordCount = maxRecordCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchTransactionsResponse", Namespace="http://www.eClaimLink.ae/", Order=0)]
        public DHPO_Auditor.DHPO.SearchTransactionsResponseBody Body;
        
        public SearchTransactionsResponse() {
        }
        
        public SearchTransactionsResponse(DHPO_Auditor.DHPO.SearchTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.eClaimLink.ae/")]
    public partial class SearchTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SearchTransactionsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string foundTransactions;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public SearchTransactionsResponseBody() {
        }
        
        public SearchTransactionsResponseBody(int SearchTransactionsResult, string foundTransactions, string errorMessage) {
            this.SearchTransactionsResult = SearchTransactionsResult;
            this.foundTransactions = foundTransactions;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateTransactionsSoapChannel : DHPO_Auditor.DHPO.ValidateTransactionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateTransactionsSoapClient : System.ServiceModel.ClientBase<DHPO_Auditor.DHPO.ValidateTransactionsSoap>, DHPO_Auditor.DHPO.ValidateTransactionsSoap {
        
        public ValidateTransactionsSoapClient() {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTransactionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateTransactionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.GetNewTransactionsResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.GetNewTransactions(DHPO_Auditor.DHPO.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactions(request);
        }
        
        public int GetNewTransactions(string login, string pwd, out string xmlTransaction, out string errorMessage) {
            DHPO_Auditor.DHPO.GetNewTransactionsRequest inValue = new DHPO_Auditor.DHPO.GetNewTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            DHPO_Auditor.DHPO.GetNewTransactionsResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).GetNewTransactions(inValue);
            xmlTransaction = retVal.Body.xmlTransaction;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewTransactionsResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.GetNewTransactionsAsync(DHPO_Auditor.DHPO.GetNewTransactionsRequest request) {
            return base.Channel.GetNewTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewTransactionsResponse> GetNewTransactionsAsync(string login, string pwd) {
            DHPO_Auditor.DHPO.GetNewTransactionsRequest inValue = new DHPO_Auditor.DHPO.GetNewTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.GetNewTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).GetNewTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.GetNewPriorAuthorizationTransactions(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactions(request);
        }
        
        public int GetNewPriorAuthorizationTransactions(string login, string pwd, out string xmlTransaction, out string errorMessage) {
            DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest inValue = new DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).GetNewPriorAuthorizationTransactions(inValue);
            xmlTransaction = retVal.Body.xmlTransaction;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.GetNewPriorAuthorizationTransactionsAsync(DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.GetNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsResponse> GetNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest inValue = new DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.GetNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).GetNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.UploadTransactionResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.UploadTransaction(DHPO_Auditor.DHPO.UploadTransactionRequest request) {
            return base.Channel.UploadTransaction(request);
        }
        
        public int UploadTransaction(string login, string pwd, byte[] fileContent, string fileName, out string errorMessage, out byte[] errorReport) {
            DHPO_Auditor.DHPO.UploadTransactionRequest inValue = new DHPO_Auditor.DHPO.UploadTransactionRequest();
            inValue.Body = new DHPO_Auditor.DHPO.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            DHPO_Auditor.DHPO.UploadTransactionResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).UploadTransaction(inValue);
            errorMessage = retVal.Body.errorMessage;
            errorReport = retVal.Body.errorReport;
            return retVal.Body.UploadTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.UploadTransactionResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.UploadTransactionAsync(DHPO_Auditor.DHPO.UploadTransactionRequest request) {
            return base.Channel.UploadTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.UploadTransactionResponse> UploadTransactionAsync(string login, string pwd, byte[] fileContent, string fileName) {
            DHPO_Auditor.DHPO.UploadTransactionRequest inValue = new DHPO_Auditor.DHPO.UploadTransactionRequest();
            inValue.Body = new DHPO_Auditor.DHPO.UploadTransactionRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileContent = fileContent;
            inValue.Body.fileName = fileName;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).UploadTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.DownloadTransactionFileResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.DownloadTransactionFile(DHPO_Auditor.DHPO.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFile(request);
        }
        
        public int DownloadTransactionFile(string login, string pwd, string fileId, out string fileName, out byte[] file, out string errorMessage) {
            DHPO_Auditor.DHPO.DownloadTransactionFileRequest inValue = new DHPO_Auditor.DHPO.DownloadTransactionFileRequest();
            inValue.Body = new DHPO_Auditor.DHPO.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            DHPO_Auditor.DHPO.DownloadTransactionFileResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).DownloadTransactionFile(inValue);
            fileName = retVal.Body.fileName;
            file = retVal.Body.file;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DownloadTransactionFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.DownloadTransactionFileResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.DownloadTransactionFileAsync(DHPO_Auditor.DHPO.DownloadTransactionFileRequest request) {
            return base.Channel.DownloadTransactionFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.DownloadTransactionFileResponse> DownloadTransactionFileAsync(string login, string pwd, string fileId) {
            DHPO_Auditor.DHPO.DownloadTransactionFileRequest inValue = new DHPO_Auditor.DHPO.DownloadTransactionFileRequest();
            inValue.Body = new DHPO_Auditor.DHPO.DownloadTransactionFileRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fileId = fileId;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).DownloadTransactionFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.CheckForNewPriorAuthorizationTransactions(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactions(request);
        }
        
        public int CheckForNewPriorAuthorizationTransactions(string login, string pwd, out string errorMessage) {
            DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest inValue = new DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).CheckForNewPriorAuthorizationTransactions(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.CheckForNewPriorAuthorizationTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.CheckForNewPriorAuthorizationTransactionsAsync(DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest request) {
            return base.Channel.CheckForNewPriorAuthorizationTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsResponse> CheckForNewPriorAuthorizationTransactionsAsync(string login, string pwd) {
            DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest inValue = new DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.CheckForNewPriorAuthorizationTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).CheckForNewPriorAuthorizationTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.SetTransactionDownloadedResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.SetTransactionDownloaded(DHPO_Auditor.DHPO.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloaded(request);
        }
        
        public int SetTransactionDownloaded(string login, string pwd, string fieldId, out string errorMessage) {
            DHPO_Auditor.DHPO.SetTransactionDownloadedRequest inValue = new DHPO_Auditor.DHPO.SetTransactionDownloadedRequest();
            inValue.Body = new DHPO_Auditor.DHPO.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fieldId = fieldId;
            DHPO_Auditor.DHPO.SetTransactionDownloadedResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).SetTransactionDownloaded(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SetTransactionDownloadedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SetTransactionDownloadedResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.SetTransactionDownloadedAsync(DHPO_Auditor.DHPO.SetTransactionDownloadedRequest request) {
            return base.Channel.SetTransactionDownloadedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SetTransactionDownloadedResponse> SetTransactionDownloadedAsync(string login, string pwd, string fieldId) {
            DHPO_Auditor.DHPO.SetTransactionDownloadedRequest inValue = new DHPO_Auditor.DHPO.SetTransactionDownloadedRequest();
            inValue.Body = new DHPO_Auditor.DHPO.SetTransactionDownloadedRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.fieldId = fieldId;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).SetTransactionDownloadedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DHPO_Auditor.DHPO.SearchTransactionsResponse DHPO_Auditor.DHPO.ValidateTransactionsSoap.SearchTransactions(DHPO_Auditor.DHPO.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactions(request);
        }
        
        public int SearchTransactions(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount, out string foundTransactions, out string errorMessage) {
            DHPO_Auditor.DHPO.SearchTransactionsRequest inValue = new DHPO_Auditor.DHPO.SearchTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.TransactionStatus = TransactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            DHPO_Auditor.DHPO.SearchTransactionsResponse retVal = ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).SearchTransactions(inValue);
            foundTransactions = retVal.Body.foundTransactions;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.SearchTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SearchTransactionsResponse> DHPO_Auditor.DHPO.ValidateTransactionsSoap.SearchTransactionsAsync(DHPO_Auditor.DHPO.SearchTransactionsRequest request) {
            return base.Channel.SearchTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DHPO_Auditor.DHPO.SearchTransactionsResponse> SearchTransactionsAsync(string login, string pwd, int direction, string callerLicense, string ePartner, int transactionID, int TransactionStatus, string transactionFileName, string transactionFromDate, string transactionToDate, int minRecordCount, int maxRecordCount) {
            DHPO_Auditor.DHPO.SearchTransactionsRequest inValue = new DHPO_Auditor.DHPO.SearchTransactionsRequest();
            inValue.Body = new DHPO_Auditor.DHPO.SearchTransactionsRequestBody();
            inValue.Body.login = login;
            inValue.Body.pwd = pwd;
            inValue.Body.direction = direction;
            inValue.Body.callerLicense = callerLicense;
            inValue.Body.ePartner = ePartner;
            inValue.Body.transactionID = transactionID;
            inValue.Body.TransactionStatus = TransactionStatus;
            inValue.Body.transactionFileName = transactionFileName;
            inValue.Body.transactionFromDate = transactionFromDate;
            inValue.Body.transactionToDate = transactionToDate;
            inValue.Body.minRecordCount = minRecordCount;
            inValue.Body.maxRecordCount = maxRecordCount;
            return ((DHPO_Auditor.DHPO.ValidateTransactionsSoap)(this)).SearchTransactionsAsync(inValue);
        }
    }
}
